[package]
name = "conllu-utils"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[[bin]]
name = "conllu"
path = "src/main.rs"

[dependencies]
clap = "2"
conllu = "0.2"
flate2 = "1"
itertools = "0.9"
stdinout = "0.4"
rand = "0.7"
rand_xorshift = "0.2"